### ISSUE TITLE
The Automate Server Parameter Was Not Entered or Inaccessible

### ISSUE THREAD

**Issue by HappyEarthDay** [Braingears/PowerShell#5]
Hello,

I've been getting this error for a while now across all of my environments when using the Push-Automate Cmdlet: 
> The Automate Server Parameter Was Not Entered or Inaccessible

I believe this has to do with how the Cmdlet is verifying the instance of Automate.  We are hosted, so we don't have much control over it. 

`Get-ADComputerNames | Push-Automate -Server $FQDN -LocationID $LocationID -User $User -Pass $Pass -Show -Transcript -Token $installerToken`

I get the same error when simply using: `Push-Automate -Server "OurSubdomain.hostedrmm.com" -LocationID 85`

Thanks so much for all you do!

**Comment by Braingears** [comment]
Due to the security changes made by ConnectWise, the agent installer can no longer be downloaded anonymously, and a token is now required. I've updated the Get-Help to reflect the required changes. 

An Automate Script can not create the tokens for you. You can get a copy at: 
https://www.mspgeek.com/topic/5373-deploy-agents-automate-scripts/
